const menuBtn=document.querySelector('.menu-toggle');const menu=document.querySelector('.menu');if(menuBtn&&menu)menuBtn.addEventListener('click',()=>menu.classList.toggle('open'));
const intro=document.querySelector('#energy-intro');if(intro){setTimeout(()=>intro.classList.add('leave'),900);setTimeout(()=>intro.remove(),1700)}
const obs=new IntersectionObserver((entries)=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
const deptData={
'11':{name:'Aude (11)',text:'Études photovoltaïques, électricité et maintenance selon la localisation et la nature du projet.'},
'30':{name:'Gard (30)',text:'Projets photovoltaïques et électriques étudiés au cas par cas selon les contraintes du site.'},
'34':{name:'Hérault (34)',text:'Études photovoltaïques, installations électriques et maintenance selon la nature et la localisation du projet.'},
'66':{name:'Pyrénées-Orientales (66)',text:'Interventions possibles sur projets solaires, électriques et opérations de maintenance.'}}
function selectDept(id){document.querySelectorAll('[data-dept]').forEach(x=>x.classList.toggle('active',x.dataset.dept===id));const d=deptData[id];if(!d)return;const ht=document.querySelector('#home-dept-title'),hx=document.querySelector('#home-dept-text'),st=document.querySelector('#sector-title'),sx=document.querySelector('#sector-text');if(ht)ht.textContent=d.name;if(hx)hx.textContent=d.text;if(st)st.textContent=d.name;if(sx)sx.textContent=d.text}
document.querySelectorAll('[data-dept]').forEach(x=>x.addEventListener('click',()=>selectDept(x.dataset.dept)));
const p=document.querySelector('#sim-power'),price=document.querySelector('#sim-price');function euro(n){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n)+' €'}function calc(){if(!p||!price)return;const kw=Number(p.value),pr=Number(price.value);document.querySelector('#power-value').textContent=kw;document.querySelector('#price-value').textContent=pr.toFixed(2).replace('.',',');const prod=kw*1350;const self=.6;const save=prod*self*pr;const budget=kw<=9?kw*1900:kw*1650;const pay=budget/Math.max(save,1);const gain=save*25-budget;document.querySelector('#sim-prod').textContent=new Intl.NumberFormat('fr-FR').format(Math.round(prod))+' kWh';document.querySelector('#sim-save').textContent=euro(save);document.querySelector('#sim-budget').textContent=euro(budget);document.querySelector('#sim-payback').textContent=pay.toFixed(1).replace('.',',')+' ans';document.querySelector('#sim-gain').textContent=euro(gain)}[p,price].forEach(x=>x&&x.addEventListener('input',calc));calc();
