const KEY='tauveron-sud-leads-v1';
const loginView=document.querySelector('#login-view');const dashboard=document.querySelector('#dashboard');const loginForm=document.querySelector('#login-form');const loginError=document.querySelector('#login-error');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function openDashboard(){sessionStorage.setItem('tauveron-pro','1');loginView.style.display='none';dashboard.style.display='block';dashboard.setAttribute('aria-hidden','false');render()}
function closeDashboard(){sessionStorage.removeItem('tauveron-pro');dashboard.style.display='none';dashboard.setAttribute('aria-hidden','true');loginView.style.display='block';document.querySelector('#access-code')?.focus()}
if(sessionStorage.getItem('tauveron-pro')==='1')openDashboard();
loginForm?.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='';const btn=loginForm.querySelector('button');btn.disabled=true;btn.textContent='Vérification…';try{const code=new FormData(loginForm).get('code');const r=await fetch('/api/pro-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});if(!r.ok)throw new Error('Code incorrect');openDashboard();loginForm.reset()}catch(err){loginError.textContent='Code d’accès incorrect.'}finally{btn.disabled=false;btn.textContent='Se connecter'}});
document.querySelector('#logout-btn')?.addEventListener('click',closeDashboard);
function getLeads(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function saveLeads(leads){localStorage.setItem(KEY,JSON.stringify(leads))}
function label(status){return({nouveau:'Nouveau',rappel:'À rappeler',devis:'Devis',gagne:'Gagné',perdu:'Perdu'})[status]||status}
function render(){const leads=getLeads();document.querySelector('#stat-total').textContent=leads.length;document.querySelector('#stat-call').textContent=leads.filter(x=>x.status==='rappel').length;document.querySelector('#stat-quote').textContent=leads.filter(x=>x.status==='devis').length;document.querySelector('#stat-won').textContent=leads.filter(x=>x.status==='gagne').length;const filter=document.querySelector('#filter-status')?.value||'all';const visible=filter==='all'?leads:leads.filter(x=>x.status===filter);const list=document.querySelector('#lead-list');const empty=document.querySelector('#empty-leads');list.innerHTML=visible.map(x=>`<article class="lead" data-id="${x.id}"><div class="lead-main"><div class="lead-top"><strong>${esc(x.name)}</strong><span class="status status-${esc(x.status)}">${esc(label(x.status))}</span></div><small>${esc(x.project)}${x.phone?' · '+esc(x.phone):''}${x.email?' · '+esc(x.email):''}</small>${x.note?`<p>${esc(x.note)}</p>`:''}<small>Ajouté le ${esc(x.created)}</small></div><div class="lead-actions"><select class="lead-status" aria-label="Changer le statut"><option value="nouveau" ${x.status==='nouveau'?'selected':''}>Nouveau</option><option value="rappel" ${x.status==='rappel'?'selected':''}>À rappeler</option><option value="devis" ${x.status==='devis'?'selected':''}>Devis</option><option value="gagne" ${x.status==='gagne'?'selected':''}>Gagné</option><option value="perdu" ${x.status==='perdu'?'selected':''}>Perdu</option></select><button class="danger delete-lead" type="button">Supprimer</button></div></article>`).join('');empty.style.display=visible.length?'none':'block';list.querySelectorAll('.lead-status').forEach(el=>el.addEventListener('change',e=>{const id=e.target.closest('.lead').dataset.id;const next=getLeads().map(x=>x.id===id?{...x,status:e.target.value}:x);saveLeads(next);render()}));list.querySelectorAll('.delete-lead').forEach(el=>el.addEventListener('click',e=>{const id=e.target.closest('.lead').dataset.id;saveLeads(getLeads().filter(x=>x.id!==id));render()}))}
document.querySelector('#lead-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const lead={id:(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)),name:f.get('name'),phone:f.get('phone'),email:f.get('email'),project:f.get('project'),status:f.get('status'),note:f.get('note'),created:new Intl.DateTimeFormat('fr-FR').format(new Date())};const leads=getLeads();leads.unshift(lead);saveLeads(leads);e.target.reset();render()});
document.querySelector('#filter-status')?.addEventListener('change',render);
document.querySelector('#export-btn')?.addEventListener('click',()=>{const leads=getLeads();if(!leads.length)return;const cols=['Nom','Téléphone','Email','Projet','Statut','Notes','Date'];const rows=leads.map(x=>[x.name,x.phone,x.email,x.project,label(x.status),x.note,x.created]);const csv=[cols,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tauveron-prospects.csv';a.click();URL.revokeObjectURL(a.href)});
